// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCN4PAD_SV1wtHCP-6dj7qHowlbTGTYqc',
    appId: '1:233229505013:web:8a97f6e5b18c0c9b5150bc',
    messagingSenderId: '233229505013',
    projectId: 'flutterprojektapp',
    authDomain: 'flutterprojektapp.firebaseapp.com',
    storageBucket: 'flutterprojektapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtyrpCTUliy_5PQ9tTDyZAsHQTPvZ-4l0',
    appId: '1:233229505013:android:9693773ab5c028b85150bc',
    messagingSenderId: '233229505013',
    projectId: 'flutterprojektapp',
    storageBucket: 'flutterprojektapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Vg81wr-7cIuy2v4yuwBrlGgdCWA-lho',
    appId: '1:233229505013:ios:a19450c2091e96705150bc',
    messagingSenderId: '233229505013',
    projectId: 'flutterprojektapp',
    storageBucket: 'flutterprojektapp.appspot.com',
    iosBundleId: 'com.example.firstly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3Vg81wr-7cIuy2v4yuwBrlGgdCWA-lho',
    appId: '1:233229505013:ios:63aba2725deefbf95150bc',
    messagingSenderId: '233229505013',
    projectId: 'flutterprojektapp',
    storageBucket: 'flutterprojektapp.appspot.com',
    iosBundleId: 'com.example.firstly.RunnerTests',
  );
}
